version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: todolist-backend
    depends_on:
      - database
    env_file:
      ./env/backend.env

  frontend:
    build:
      context: ../TodoList-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: todolist-frontend
    depends_on:
      - backend

  database:
    image: 'postgres:14-alpine'
    ports:
      - "5432:5432"
    container_name: todolist-database
    env_file:
      ./env/postgres.env
    volumes:
      - todolist_data:/var/lib/postgresql/data
volumes:
  todolist_data: