version: '3.7'

services:
  app-server:
    build:
      context: TodoList-backend
      dockerfile: Dockerfile
    ports:
      - "9080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todolist
      - SPRING_DATASOURCE_USERNAME=todolist
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: TodoList-frontend
      dockerfile: Dockerfile
    ports:
      - "9090:3000"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

  db:
    image: 'postgres:14-alpine'
    ports:
      - "5462:5432"
    environment:
      - POSTGRES_USER=todolist
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todolist
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend: